const double STANDART_BUTTON_HEIGHT = 50;
const double STANDART_BUTTON_WIDTH = 300;

const double STANDART_BUTTON_ROUNDNESS = 15;
const double STANDART_ICON_SIZE = 30;

const double FLOW_SLIDER_HIGHT = 180;
const double FLOW_SLIDER_INDICATOR_HIGHT = 20;
const double STANDART_TEXT_HORIZONTAL_PADDING = 20;
